### PR TITLE
fix(apy): use 365 days

### PR DESCRIPTION
**Pull request by Rubilmax**

### CODE REVIEW

**Review by Jean-Grimal — APPROVED** [review]

**Review by QGarchery — CHANGES_REQUESTED** [review]
I'm not familiar with this repo but it should not have gone through the tests, and this PR should not either. It seems like there were multiple mistakes made in the computation

**Comment by MerlinEgalite** [comment]
True maybe we can add tests @tomrpl @Jean-Grimal ?

**Review by julien-devatom — COMMENTED** [review]
this is the supply rate per second that should be compounded no? 
$$e^{r_b * (1 - u) * 365 days} - 1 \not =  (e^{r_b * 365 days} - 1) * (1 - u)$$

**Comment by MerlinEgalite** [comment]
In the code we first compound the `borrowRate` to compute interest and then the interest is distributed among supplier, so I think the code of the snippet is correct

**Comment by MerlinEgalite** [comment]
Merging this because main is obviously wrong. Tests must be added though but there's an issue for that already

**Pull request merged**
